#include<stdio.h>
#include<conio.h>
#include<stdlib.h>
#include<process.h>
#define maxsize 30

int stack[maxsize],top;
void push();
void pop();
void display();

void main()
{
clrscr();
int ch=1,top=-1;
while(ch)
{
printf("\n push");
printf("\n pop");
printf("\n Enter your choice");
scanf("%d",&ch);
switch(ch)
{
case 1:
push();
break;
case 2:
pop();
break;
default:
exit(0);
}
}
getch();
}
void push()
{
int n;
if(top==maxsize-1)
{
printf("\n Stack Overflow");
return;
}
top++;
printf("\n Enter number:\n");
scanf("%d",&n);
stack[top]=n;
printf("\n Elements in stack are:\n");
display();
}
void pop()
{
int n;
if(top==-1)
{
printf("\n Stack Underflow");
return;
}
else
{
top--;
printf("\n Elements in stack are:\n");
display();
}
}
void display()
{
int i;
for(i=0;i<=top;i++)
{
printf("%d\n",stack[i]);
}
}